with-expecter: true
disable-version-string: true
outpkg: mock
filename: "{{.InterfaceName}}.go"
mockname: "{{.InterfaceName}}"
dir: "{{.InterfaceDir}}/mock"
packages:
  gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/application/command:
    config:
      all: true
