// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/pkg/trackerapi"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// AddLink provides a mock function for the type MockClient
func (_mock *MockClient) AddLink(ctx context.Context, chatID int64, request trackerapi.AddLinkRequest) (trackerapi.LinkResponse, error) {
	ret := _mock.Called(ctx, chatID, request)

	if len(ret) == 0 {
		panic("no return value specified for AddLink")
	}

	var r0 trackerapi.LinkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, trackerapi.AddLinkRequest) (trackerapi.LinkResponse, error)); ok {
		return returnFunc(ctx, chatID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, trackerapi.AddLinkRequest) trackerapi.LinkResponse); ok {
		r0 = returnFunc(ctx, chatID, request)
	} else {
		r0 = ret.Get(0).(trackerapi.LinkResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, trackerapi.AddLinkRequest) error); ok {
		r1 = returnFunc(ctx, chatID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_AddLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLink'
type MockClient_AddLink_Call struct {
	*mock.Call
}

// AddLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - request trackerapi.AddLinkRequest
func (_e *MockClient_Expecter) AddLink(ctx interface{}, chatID interface{}, request interface{}) *MockClient_AddLink_Call {
	return &MockClient_AddLink_Call{Call: _e.mock.On("AddLink", ctx, chatID, request)}
}

func (_c *MockClient_AddLink_Call) Run(run func(ctx context.Context, chatID int64, request trackerapi.AddLinkRequest)) *MockClient_AddLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 trackerapi.AddLinkRequest
		if args[2] != nil {
			arg2 = args[2].(trackerapi.AddLinkRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_AddLink_Call) Return(linkResponse trackerapi.LinkResponse, err error) *MockClient_AddLink_Call {
	_c.Call.Return(linkResponse, err)
	return _c
}

func (_c *MockClient_AddLink_Call) RunAndReturn(run func(ctx context.Context, chatID int64, request trackerapi.AddLinkRequest) (trackerapi.LinkResponse, error)) *MockClient_AddLink_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteChat provides a mock function for the type MockClient
func (_mock *MockClient) DeleteChat(ctx context.Context, chatID int64) error {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteChat'
type MockClient_DeleteChat_Call struct {
	*mock.Call
}

// DeleteChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockClient_Expecter) DeleteChat(ctx interface{}, chatID interface{}) *MockClient_DeleteChat_Call {
	return &MockClient_DeleteChat_Call{Call: _e.mock.On("DeleteChat", ctx, chatID)}
}

func (_c *MockClient_DeleteChat_Call) Run(run func(ctx context.Context, chatID int64)) *MockClient_DeleteChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_DeleteChat_Call) Return(err error) *MockClient_DeleteChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteChat_Call) RunAndReturn(run func(ctx context.Context, chatID int64) error) *MockClient_DeleteChat_Call {
	_c.Call.Return(run)
	return _c
}

// ListLinks provides a mock function for the type MockClient
func (_mock *MockClient) ListLinks(ctx context.Context, chatID int64) (trackerapi.ListLinksResponse, error) {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for ListLinks")
	}

	var r0 trackerapi.ListLinksResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) (trackerapi.ListLinksResponse, error)); ok {
		return returnFunc(ctx, chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) trackerapi.ListLinksResponse); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Get(0).(trackerapi.ListLinksResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = returnFunc(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListLinks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListLinks'
type MockClient_ListLinks_Call struct {
	*mock.Call
}

// ListLinks is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockClient_Expecter) ListLinks(ctx interface{}, chatID interface{}) *MockClient_ListLinks_Call {
	return &MockClient_ListLinks_Call{Call: _e.mock.On("ListLinks", ctx, chatID)}
}

func (_c *MockClient_ListLinks_Call) Run(run func(ctx context.Context, chatID int64)) *MockClient_ListLinks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ListLinks_Call) Return(listLinksResponse trackerapi.ListLinksResponse, err error) *MockClient_ListLinks_Call {
	_c.Call.Return(listLinksResponse, err)
	return _c
}

func (_c *MockClient_ListLinks_Call) RunAndReturn(run func(ctx context.Context, chatID int64) (trackerapi.ListLinksResponse, error)) *MockClient_ListLinks_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterChat provides a mock function for the type MockClient
func (_mock *MockClient) RegisterChat(ctx context.Context, chatID int64) error {
	ret := _mock.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for RegisterChat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = returnFunc(ctx, chatID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_RegisterChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterChat'
type MockClient_RegisterChat_Call struct {
	*mock.Call
}

// RegisterChat is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *MockClient_Expecter) RegisterChat(ctx interface{}, chatID interface{}) *MockClient_RegisterChat_Call {
	return &MockClient_RegisterChat_Call{Call: _e.mock.On("RegisterChat", ctx, chatID)}
}

func (_c *MockClient_RegisterChat_Call) Run(run func(ctx context.Context, chatID int64)) *MockClient_RegisterChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_RegisterChat_Call) Return(err error) *MockClient_RegisterChat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_RegisterChat_Call) RunAndReturn(run func(ctx context.Context, chatID int64) error) *MockClient_RegisterChat_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveLink provides a mock function for the type MockClient
func (_mock *MockClient) RemoveLink(ctx context.Context, chatID int64, request trackerapi.RemoveLinkRequest) (trackerapi.LinkResponse, error) {
	ret := _mock.Called(ctx, chatID, request)

	if len(ret) == 0 {
		panic("no return value specified for RemoveLink")
	}

	var r0 trackerapi.LinkResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, trackerapi.RemoveLinkRequest) (trackerapi.LinkResponse, error)); ok {
		return returnFunc(ctx, chatID, request)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, trackerapi.RemoveLinkRequest) trackerapi.LinkResponse); ok {
		r0 = returnFunc(ctx, chatID, request)
	} else {
		r0 = ret.Get(0).(trackerapi.LinkResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, trackerapi.RemoveLinkRequest) error); ok {
		r1 = returnFunc(ctx, chatID, request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_RemoveLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveLink'
type MockClient_RemoveLink_Call struct {
	*mock.Call
}

// RemoveLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - request trackerapi.RemoveLinkRequest
func (_e *MockClient_Expecter) RemoveLink(ctx interface{}, chatID interface{}, request interface{}) *MockClient_RemoveLink_Call {
	return &MockClient_RemoveLink_Call{Call: _e.mock.On("RemoveLink", ctx, chatID, request)}
}

func (_c *MockClient_RemoveLink_Call) Run(run func(ctx context.Context, chatID int64, request trackerapi.RemoveLinkRequest)) *MockClient_RemoveLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 trackerapi.RemoveLinkRequest
		if args[2] != nil {
			arg2 = args[2].(trackerapi.RemoveLinkRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockClient_RemoveLink_Call) Return(linkResponse trackerapi.LinkResponse, err error) *MockClient_RemoveLink_Call {
	_c.Call.Return(linkResponse, err)
	return _c
}

func (_c *MockClient_RemoveLink_Call) RunAndReturn(run func(ctx context.Context, chatID int64, request trackerapi.RemoveLinkRequest) (trackerapi.LinkResponse, error)) *MockClient_RemoveLink_Call {
	_c.Call.Return(run)
	return _c
}
