// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/bot/adapters/gateway/repository"
)

// NewMockSessionRepository creates a new instance of MockSessionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionRepository {
	mock := &MockSessionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })
	return mock
}

// MockSessionRepository is an autogenerated mock type for the SessionRepository type
type MockSessionRepository struct {
	mock.Mock
}

type MockSessionRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionRepository) EXPECT() *MockSessionRepository_Expecter {
	return &MockSessionRepository_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Clear(chatID int64) {
	_mock.Called(chatID)
	return
}

// MockSessionRepository_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockSessionRepository_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - chatID int64
func (_e *MockSessionRepository_Expecter) Clear(chatID interface{}) *MockSessionRepository_Clear_Call {
	return &MockSessionRepository_Clear_Call{Call: _e.mock.On("Clear", chatID)}
}

func (_c *MockSessionRepository_Clear_Call) Run(run func(chatID int64)) *MockSessionRepository_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Clear_Call) Return() *MockSessionRepository_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRepository_Clear_Call) RunAndReturn(run func(chatID int64)) *MockSessionRepository_Clear_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Get(chatID int64) (repository.Session, bool) {
	ret := _mock.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 repository.Session
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(int64) (repository.Session, bool)); ok {
		return returnFunc(chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) repository.Session); ok {
		r0 = returnFunc(chatID)
	} else {
		r0 = ret.Get(0).(repository.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) bool); ok {
		r1 = returnFunc(chatID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSessionRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - chatID int64
func (_e *MockSessionRepository_Expecter) Get(chatID interface{}) *MockSessionRepository_Get_Call {
	return &MockSessionRepository_Get_Call{Call: _e.mock.On("Get", chatID)}
}

func (_c *MockSessionRepository_Get_Call) Run(run func(chatID int64)) *MockSessionRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Get_Call) Return(session repository.Session, b bool) *MockSessionRepository_Get_Call {
	_c.Call.Return(session, b)
	return _c
}

func (_c *MockSessionRepository_Get_Call) RunAndReturn(run func(chatID int64) (repository.Session, bool)) *MockSessionRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockSessionRepository
func (_mock *MockSessionRepository) Set(chatID int64, session repository.Session) {
	_mock.Called(chatID, session)
	return
}

// MockSessionRepository_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSessionRepository_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - chatID int64
//   - session repository.Session
func (_e *MockSessionRepository_Expecter) Set(chatID interface{}, session interface{}) *MockSessionRepository_Set_Call {
	return &MockSessionRepository_Set_Call{Call: _e.mock.On("Set", chatID, session)}
}

func (_c *MockSessionRepository_Set_Call) Run(run func(chatID int64, session repository.Session)) *MockSessionRepository_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 repository.Session
		if args[1] != nil {
			arg1 = args[1].(repository.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionRepository_Set_Call) Return() *MockSessionRepository_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionRepository_Set_Call) RunAndReturn(run func(chatID int64, session repository.Session)) *MockSessionRepository_Set_Call {
	_c.Run(run)
	return _c
}
