// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: scrapper/v1/scrapper.proto

package scrapperv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChatRequest) Reset() {
	*x = RegisterChatRequest{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChatRequest) ProtoMessage() {}

func (x *RegisterChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChatRequest.ProtoReflect.Descriptor instead.
func (*RegisterChatRequest) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type RegisterChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterChatResponse) Reset() {
	*x = RegisterChatResponse{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterChatResponse) ProtoMessage() {}

func (x *RegisterChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterChatResponse.ProtoReflect.Descriptor instead.
func (*RegisterChatResponse) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{1}
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteChatRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type DeleteChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatResponse) Reset() {
	*x = DeleteChatResponse{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatResponse) ProtoMessage() {}

func (x *DeleteChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatResponse.ProtoReflect.Descriptor instead.
func (*DeleteChatResponse) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{3}
}

type AddLinkPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Filters       []string               `protobuf:"bytes,3,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinkPayload) Reset() {
	*x = AddLinkPayload{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkPayload) ProtoMessage() {}

func (x *AddLinkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkPayload.ProtoReflect.Descriptor instead.
func (*AddLinkPayload) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{4}
}

func (x *AddLinkPayload) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *AddLinkPayload) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AddLinkPayload) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type AddLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Body          *AddLinkPayload        `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinkRequest) Reset() {
	*x = AddLinkRequest{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkRequest) ProtoMessage() {}

func (x *AddLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkRequest.ProtoReflect.Descriptor instead.
func (*AddLinkRequest) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{5}
}

func (x *AddLinkRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *AddLinkRequest) GetBody() *AddLinkPayload {
	if x != nil {
		return x.Body
	}
	return nil
}

type RemoveLinkPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLinkPayload) Reset() {
	*x = RemoveLinkPayload{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLinkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLinkPayload) ProtoMessage() {}

func (x *RemoveLinkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLinkPayload.ProtoReflect.Descriptor instead.
func (*RemoveLinkPayload) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveLinkPayload) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type RemoveLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Body          *RemoveLinkPayload     `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLinkRequest) Reset() {
	*x = RemoveLinkRequest{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLinkRequest) ProtoMessage() {}

func (x *RemoveLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLinkRequest.ProtoReflect.Descriptor instead.
func (*RemoveLinkRequest) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveLinkRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *RemoveLinkRequest) GetBody() *RemoveLinkPayload {
	if x != nil {
		return x.Body
	}
	return nil
}

type LinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Filters       []string               `protobuf:"bytes,4,rep,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkResponse) Reset() {
	*x = LinkResponse{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkResponse) ProtoMessage() {}

func (x *LinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkResponse.ProtoReflect.Descriptor instead.
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{8}
}

func (x *LinkResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *LinkResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *LinkResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LinkResponse) GetFilters() []string {
	if x != nil {
		return x.Filters
	}
	return nil
}

type AddLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *LinkResponse          `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddLinkResponse) Reset() {
	*x = AddLinkResponse{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLinkResponse) ProtoMessage() {}

func (x *AddLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLinkResponse.ProtoReflect.Descriptor instead.
func (*AddLinkResponse) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{9}
}

func (x *AddLinkResponse) GetLink() *LinkResponse {
	if x != nil {
		return x.Link
	}
	return nil
}

type RemoveLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *LinkResponse          `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveLinkResponse) Reset() {
	*x = RemoveLinkResponse{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveLinkResponse) ProtoMessage() {}

func (x *RemoveLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveLinkResponse.ProtoReflect.Descriptor instead.
func (*RemoveLinkResponse) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveLinkResponse) GetLink() *LinkResponse {
	if x != nil {
		return x.Link
	}
	return nil
}

type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{11}
}

func (x *ListLinksRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*LinkResponse        `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scrapper_v1_scrapper_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_scrapper_v1_scrapper_proto_rawDescGZIP(), []int{12}
}

func (x *ListLinksResponse) GetLinks() []*LinkResponse {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListLinksResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_scrapper_v1_scrapper_proto protoreflect.FileDescriptor

const file_scrapper_v1_scrapper_proto_rawDesc = "" +
	"\n" +
	"\x1ascrapper/v1/scrapper.proto\x12\vscrapper.v1\".\n" +
	"\x13RegisterChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"\x16\n" +
	"\x14RegisterChatResponse\",\n" +
	"\x11DeleteChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"\x14\n" +
	"\x12DeleteChatResponse\"R\n" +
	"\x0eAddLinkPayload\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\afilters\x18\x03 \x03(\tR\afilters\"Z\n" +
	"\x0eAddLinkRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12/\n" +
	"\x04body\x18\x02 \x01(\v2\x1b.scrapper.v1.AddLinkPayloadR\x04body\"'\n" +
	"\x11RemoveLinkPayload\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\"`\n" +
	"\x11RemoveLinkRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x122\n" +
	"\x04body\x18\x02 \x01(\v2\x1e.scrapper.v1.RemoveLinkPayloadR\x04body\"^\n" +
	"\fLinkResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\afilters\x18\x04 \x03(\tR\afilters\"@\n" +
	"\x0fAddLinkResponse\x12-\n" +
	"\x04link\x18\x01 \x01(\v2\x19.scrapper.v1.LinkResponseR\x04link\"C\n" +
	"\x12RemoveLinkResponse\x12-\n" +
	"\x04link\x18\x01 \x01(\v2\x19.scrapper.v1.LinkResponseR\x04link\"+\n" +
	"\x10ListLinksRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\"X\n" +
	"\x11ListLinksResponse\x12/\n" +
	"\x05links\x18\x01 \x03(\v2\x19.scrapper.v1.LinkResponseR\x05links\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size2\x96\x03\n" +
	"\x0fScrapperService\x12S\n" +
	"\fRegisterChat\x12 .scrapper.v1.RegisterChatRequest\x1a!.scrapper.v1.RegisterChatResponse\x12M\n" +
	"\n" +
	"DeleteChat\x12\x1e.scrapper.v1.DeleteChatRequest\x1a\x1f.scrapper.v1.DeleteChatResponse\x12D\n" +
	"\aAddLink\x12\x1b.scrapper.v1.AddLinkRequest\x1a\x1c.scrapper.v1.AddLinkResponse\x12M\n" +
	"\n" +
	"RemoveLink\x12\x1e.scrapper.v1.RemoveLinkRequest\x1a\x1f.scrapper.v1.RemoveLinkResponse\x12J\n" +
	"\tListLinks\x12\x1d.scrapper.v1.ListLinksRequest\x1a\x1e.scrapper.v1.ListLinksResponseBkZigitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/api/proto/scrapper/v1;scrapperv1b\x06proto3"

var (
	file_scrapper_v1_scrapper_proto_rawDescOnce sync.Once
	file_scrapper_v1_scrapper_proto_rawDescData []byte
)

func file_scrapper_v1_scrapper_proto_rawDescGZIP() []byte {
	file_scrapper_v1_scrapper_proto_rawDescOnce.Do(func() {
		file_scrapper_v1_scrapper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scrapper_v1_scrapper_proto_rawDesc), len(file_scrapper_v1_scrapper_proto_rawDesc)))
	})
	return file_scrapper_v1_scrapper_proto_rawDescData
}

var file_scrapper_v1_scrapper_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_scrapper_v1_scrapper_proto_goTypes = []any{
	(*RegisterChatRequest)(nil),  // 0: scrapper.v1.RegisterChatRequest
	(*RegisterChatResponse)(nil), // 1: scrapper.v1.RegisterChatResponse
	(*DeleteChatRequest)(nil),    // 2: scrapper.v1.DeleteChatRequest
	(*DeleteChatResponse)(nil),   // 3: scrapper.v1.DeleteChatResponse
	(*AddLinkPayload)(nil),       // 4: scrapper.v1.AddLinkPayload
	(*AddLinkRequest)(nil),       // 5: scrapper.v1.AddLinkRequest
	(*RemoveLinkPayload)(nil),    // 6: scrapper.v1.RemoveLinkPayload
	(*RemoveLinkRequest)(nil),    // 7: scrapper.v1.RemoveLinkRequest
	(*LinkResponse)(nil),         // 8: scrapper.v1.LinkResponse
	(*AddLinkResponse)(nil),      // 9: scrapper.v1.AddLinkResponse
	(*RemoveLinkResponse)(nil),   // 10: scrapper.v1.RemoveLinkResponse
	(*ListLinksRequest)(nil),     // 11: scrapper.v1.ListLinksRequest
	(*ListLinksResponse)(nil),    // 12: scrapper.v1.ListLinksResponse
}
var file_scrapper_v1_scrapper_proto_depIdxs = []int32{
	4,  // 0: scrapper.v1.AddLinkRequest.body:type_name -> scrapper.v1.AddLinkPayload
	6,  // 1: scrapper.v1.RemoveLinkRequest.body:type_name -> scrapper.v1.RemoveLinkPayload
	8,  // 2: scrapper.v1.AddLinkResponse.link:type_name -> scrapper.v1.LinkResponse
	8,  // 3: scrapper.v1.RemoveLinkResponse.link:type_name -> scrapper.v1.LinkResponse
	8,  // 4: scrapper.v1.ListLinksResponse.links:type_name -> scrapper.v1.LinkResponse
	0,  // 5: scrapper.v1.ScrapperService.RegisterChat:input_type -> scrapper.v1.RegisterChatRequest
	2,  // 6: scrapper.v1.ScrapperService.DeleteChat:input_type -> scrapper.v1.DeleteChatRequest
	5,  // 7: scrapper.v1.ScrapperService.AddLink:input_type -> scrapper.v1.AddLinkRequest
	7,  // 8: scrapper.v1.ScrapperService.RemoveLink:input_type -> scrapper.v1.RemoveLinkRequest
	11, // 9: scrapper.v1.ScrapperService.ListLinks:input_type -> scrapper.v1.ListLinksRequest
	1,  // 10: scrapper.v1.ScrapperService.RegisterChat:output_type -> scrapper.v1.RegisterChatResponse
	3,  // 11: scrapper.v1.ScrapperService.DeleteChat:output_type -> scrapper.v1.DeleteChatResponse
	9,  // 12: scrapper.v1.ScrapperService.AddLink:output_type -> scrapper.v1.AddLinkResponse
	10, // 13: scrapper.v1.ScrapperService.RemoveLink:output_type -> scrapper.v1.RemoveLinkResponse
	12, // 14: scrapper.v1.ScrapperService.ListLinks:output_type -> scrapper.v1.ListLinksResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_scrapper_v1_scrapper_proto_init() }
func file_scrapper_v1_scrapper_proto_init() {
	if File_scrapper_v1_scrapper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scrapper_v1_scrapper_proto_rawDesc), len(file_scrapper_v1_scrapper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scrapper_v1_scrapper_proto_goTypes,
		DependencyIndexes: file_scrapper_v1_scrapper_proto_depIdxs,
		MessageInfos:      file_scrapper_v1_scrapper_proto_msgTypes,
	}.Build()
	File_scrapper_v1_scrapper_proto = out.File
	file_scrapper_v1_scrapper_proto_goTypes = nil
	file_scrapper_v1_scrapper_proto_depIdxs = nil
}
