// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/application/dialog"
)

// NewMockSessionStore creates a new instance of MockSessionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSessionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSessionStore {
	mock := &MockSessionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSessionStore is an autogenerated mock type for the SessionStore type
type MockSessionStore struct {
	mock.Mock
}

type MockSessionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSessionStore) EXPECT() *MockSessionStore_Expecter {
	return &MockSessionStore_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) Clear(chatID int64) {
	_mock.Called(chatID)
	return
}

// MockSessionStore_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type MockSessionStore_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - chatID int64
func (_e *MockSessionStore_Expecter) Clear(chatID interface{}) *MockSessionStore_Clear_Call {
	return &MockSessionStore_Clear_Call{Call: _e.mock.On("Clear", chatID)}
}

func (_c *MockSessionStore_Clear_Call) Run(run func(chatID int64)) *MockSessionStore_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionStore_Clear_Call) Return() *MockSessionStore_Clear_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionStore_Clear_Call) RunAndReturn(run func(chatID int64)) *MockSessionStore_Clear_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) Get(chatID int64) (dialog.Session, bool) {
	ret := _mock.Called(chatID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 dialog.Session
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(int64) (dialog.Session, bool)); ok {
		return returnFunc(chatID)
	}
	if returnFunc, ok := ret.Get(0).(func(int64) dialog.Session); ok {
		r0 = returnFunc(chatID)
	} else {
		r0 = ret.Get(0).(dialog.Session)
	}
	if returnFunc, ok := ret.Get(1).(func(int64) bool); ok {
		r1 = returnFunc(chatID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockSessionStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSessionStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - chatID int64
func (_e *MockSessionStore_Expecter) Get(chatID interface{}) *MockSessionStore_Get_Call {
	return &MockSessionStore_Get_Call{Call: _e.mock.On("Get", chatID)}
}

func (_c *MockSessionStore_Get_Call) Run(run func(chatID int64)) *MockSessionStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSessionStore_Get_Call) Return(session dialog.Session, b bool) *MockSessionStore_Get_Call {
	_c.Call.Return(session, b)
	return _c
}

func (_c *MockSessionStore_Get_Call) RunAndReturn(run func(chatID int64) (dialog.Session, bool)) *MockSessionStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Set provides a mock function for the type MockSessionStore
func (_mock *MockSessionStore) Set(chatID int64, session dialog.Session) {
	_mock.Called(chatID, session)
	return
}

// MockSessionStore_Set_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Set'
type MockSessionStore_Set_Call struct {
	*mock.Call
}

// Set is a helper method to define mock.On call
//   - chatID int64
//   - session dialog.Session
func (_e *MockSessionStore_Expecter) Set(chatID interface{}, session interface{}) *MockSessionStore_Set_Call {
	return &MockSessionStore_Set_Call{Call: _e.mock.On("Set", chatID, session)}
}

func (_c *MockSessionStore_Set_Call) Run(run func(chatID int64, session dialog.Session)) *MockSessionStore_Set_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 dialog.Session
		if args[1] != nil {
			arg1 = args[1].(dialog.Session)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSessionStore_Set_Call) Return() *MockSessionStore_Set_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSessionStore_Set_Call) RunAndReturn(run func(chatID int64, session dialog.Session)) *MockSessionStore_Set_Call {
	_c.Run(run)
	return _c
}
