// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/pkg/trackerapi"
)

// NewMockUpdatesSender creates a new instance of MockUpdatesSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdatesSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdatesSender {
	mock := &MockUpdatesSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUpdatesSender is an autogenerated mock type for the UpdatesSender type
type MockUpdatesSender struct {
	mock.Mock
}

type MockUpdatesSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdatesSender) EXPECT() *MockUpdatesSender_Expecter {
	return &MockUpdatesSender_Expecter{mock: &_m.Mock}
}

// SendUpdate provides a mock function for the type MockUpdatesSender
func (_mock *MockUpdatesSender) SendUpdate(ctx context.Context, update trackerapi.LinkUpdate) error {
	ret := _mock.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for SendUpdate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, trackerapi.LinkUpdate) error); ok {
		r0 = returnFunc(ctx, update)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUpdatesSender_SendUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendUpdate'
type MockUpdatesSender_SendUpdate_Call struct {
	*mock.Call
}

// SendUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - update trackerapi.LinkUpdate
func (_e *MockUpdatesSender_Expecter) SendUpdate(ctx interface{}, update interface{}) *MockUpdatesSender_SendUpdate_Call {
	return &MockUpdatesSender_SendUpdate_Call{Call: _e.mock.On("SendUpdate", ctx, update)}
}

func (_c *MockUpdatesSender_SendUpdate_Call) Run(run func(ctx context.Context, update trackerapi.LinkUpdate)) *MockUpdatesSender_SendUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 trackerapi.LinkUpdate
		if args[1] != nil {
			arg1 = args[1].(trackerapi.LinkUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUpdatesSender_SendUpdate_Call) Return(err error) *MockUpdatesSender_SendUpdate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUpdatesSender_SendUpdate_Call) RunAndReturn(run func(ctx context.Context, update trackerapi.LinkUpdate) error) *MockUpdatesSender_SendUpdate_Call {
	_c.Call.Return(run)
	return _c
}
