// Code generated by mockery. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// Command is an autogenerated mock type for the Command type
type Command struct {
	mock.Mock
}

type Command_Expecter struct {
	mock *mock.Mock
}

func (_m *Command) EXPECT() *Command_Expecter {
	return &Command_Expecter{mock: &_m.Mock}
}

// Description provides a mock function with no fields
func (_m *Command) Description() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Description")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Command_Description_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Description'
type Command_Description_Call struct {
	*mock.Call
}

// Description is a helper method to define mock.On call
func (_e *Command_Expecter) Description() *Command_Description_Call {
	return &Command_Description_Call{Call: _e.mock.On("Description")}
}

func (_c *Command_Description_Call) Run(run func()) *Command_Description_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_Description_Call) Return(_a0 string) *Command_Description_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Command_Description_Call) RunAndReturn(run func() string) *Command_Description_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *Command) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Command_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Command_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Command_Expecter) Name() *Command_Name_Call {
	return &Command_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Command_Name_Call) Run(run func()) *Command_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Command_Name_Call) Return(_a0 string) *Command_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Command_Name_Call) RunAndReturn(run func() string) *Command_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewCommand creates a new instance of Command. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *Command {
	mock := &Command{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
