// Code generated by mockery. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	command "gitlab.education.tbank.ru/backend-academy-go-2025/homeworks/link-tracker/internal/application/commands"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

type Handler_Expecter struct {
	mock *mock.Mock
}

func (_m *Handler) EXPECT() *Handler_Expecter {
	return &Handler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: update, bot
func (_m *Handler) Handle(update *tgbotapi.Update, bot command.Sender) error {
	ret := _m.Called(update, bot)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*tgbotapi.Update, command.Sender) error); ok {
		r0 = rf(update, bot)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Handler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type Handler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - update *tgbotapi.Update
//   - bot command.Sender
func (_e *Handler_Expecter) Handle(update interface{}, bot interface{}) *Handler_Handle_Call {
	return &Handler_Handle_Call{Call: _e.mock.On("Handle", update, bot)}
}

func (_c *Handler_Handle_Call) Run(run func(update *tgbotapi.Update, bot command.Sender)) *Handler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*tgbotapi.Update), args[1].(command.Sender))
	})
	return _c
}

func (_c *Handler_Handle_Call) Return(_a0 error) *Handler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Handler_Handle_Call) RunAndReturn(run func(*tgbotapi.Update, command.Sender) error) *Handler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
